//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp17
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Class { get; set; }
        public Nullable<int> Cathedra_Id { get; set; }
        public Nullable<int> Teacher_id { get; set; }
    
        public virtual Cathedras Cathedras { get; set; }
        public virtual Teachers Teachers { get; set; }
    }
}
